# Generated by Django 5.0.12 on 2025-03-06 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=45)),
                ('genero', models.CharField(max_length=45)),
                ('curp', models.CharField(max_length=45)),
                ('fecha_nac', models.DateField()),
                ('direccion', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_materia', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Colegiatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mes', models.DateField()),
                ('pagado', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TipoParentesco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre', models.PositiveSmallIntegerField()),
                ('calificacion', models.CharField(max_length=45)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoHasCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alumno')),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.calificacion')),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoHasColegiatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alumno')),
                ('colegiatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.colegiatura')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grado')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grupo'),
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('correo_e', models.CharField(max_length=45)),
                ('curp', models.CharField(max_length=45)),
                ('rfc', models.IntegerField()),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='MaestroHasGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grupo')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.maestro')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido_paterno', models.CharField(max_length=45)),
                ('apellido_materno', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('tipo_parentesco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipoparentesco')),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoHasTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alumno')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tutor')),
            ],
        ),
    ]
